kind = "web"
previewPath = "/"
title = "AnimalView"
version = "1.0.0"
id = "artifacts/animal-view"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25835

[services.development]
run = "pnpm --filter @workspace/animal-view run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/animal-view", "run", "build" ]
publicDir = "artifacts/animal-view/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25835"
BASE_PATH = "/"
